name: CI - Docker Build Check

# Define quando o script será executado
on:
  push:
    branches: [ "main", "feature/dockerizacao" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest # O GitHub vai subir uma máquina Linux para nós

    steps:
      # 1. Baixa o código do seu repositório para a máquina do GitHub
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Configura o ambiente Python (caso queira rodar testes unitários depois)
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # 3. Instala as dependências (bom para validar o requirements.txt)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Tenta buildar a imagem Docker
      # Se o seu Dockerfile estiver errado, o CI falha aqui!
      - name: Build Docker Image
        run: |
          docker build -t api-fraude-teste:${{ github.sha }} .

      # 5. (Opcional) Teste rápido: Verificando se a imagem existe
      - name: Verify Image
        run: docker images